import { SubscriptionWithDetails } from '@prisma/client';
import { NextApiRequest, NextApiResponse } from 'next';
import parseResponseDateStrings from 'utils/api/parse-response-date-strings';
import { prisma } from 'utils/prisma/init';

type Stats = {
  active: number;
  newActive: number;
  newInactive: number;
  percentageByYear: number[];
};

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  let dateFilter = req.query.dateFilter ? new Date(req.query.dateFilter as string) : null;

  if (!dateFilter) {
    dateFilter = new Date();
    dateFilter.setDate(dateFilter.getDate() - 30);
  }

  /*const subscriptionWithDetails = await prisma.subscriptionWithDetails.findMany({
    orderBy: { lastPaymentDate: 'desc' },
    distinct: ['email'],
  });*/
  const subscriptionWithDetails = parseResponseDateStrings([
    {
      id: 110,
      createdDate: '2022-03-28T02:16:31.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-03-28T02:16:31.000Z',
      status: 'active',
      stripeId: 'sub_1Ki88BKRkjW3h5nxrJIDOrsT',
      stripeCustomerId: 'cus_LOw0uSviYBCQsl',
      stripeProductId: 'prod_LOw0xUNJQbjuVW',
      userId: 96,
      userName: 'Juan Vazquez',
      productId: 40,
      productName: 'Single Tree Membership ($20/yr donation)',
      email: 'juanvme123@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 20,
      createdDate: '2020-03-06T03:50:12.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-03-06T03:50:26.000Z',
      status: 'active',
      stripeId: 'sub_GrFh4URhDrPmZX',
      stripeCustomerId: 'cus_GrFhogy7QpOZne',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 25,
      userName: 'Stacia Farrar',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'stacia.farrar@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 109,
      createdDate: '2022-03-02T01:15:26.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-03-02T01:15:26.000Z',
      status: 'active',
      stripeId: 'sub_1KYgmoKRkjW3h5nxRByHpDpc',
      stripeCustomerId: 'cus_LFB9xmv4J8mLQo',
      stripeProductId: 'prod_LFB9Tv21zs3FBE',
      userId: 95,
      userName: 'Elizabeth Halprin',
      productId: 39,
      productName: 'Grove Membership ($60/yr donation)',
      email: 'elizabethhalprin@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 35,
      createdDate: '2020-02-28T23:16:01.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-28T23:16:52.000Z',
      status: 'active',
      stripeId: 'sub_GovvZRdWd8XxfC',
      stripeCustomerId: 'cus_GovvaGgC7io6w0',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 35,
      userName: 'Kyle Hoskins',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'kyle@kylehoskins.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 12,
      createdDate: '2021-02-28T01:39:42.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-28T01:40:21.000Z',
      status: 'active',
      stripeId: 'sub_J1hfkFYdbWA16E',
      stripeCustomerId: 'cus_J1hf7RFKzhtiut',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 14,
      userName: 'Danielle Snyder',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'dksnyder41@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 38,
      createdDate: '2021-02-26T14:14:34.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-26T14:14:45.000Z',
      status: 'active',
      stripeId: 'sub_J19O7XH9enVvBG',
      stripeCustomerId: 'cus_J19O4ySL7BjKL2',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 43,
      userName: 'Sarah Welbes',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'scwelbes@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 108,
      createdDate: '2022-02-24T04:47:21.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-24T04:47:21.000Z',
      status: 'trialing',
      stripeId: 'sub_1KWZEbKRkjW3h5nxCO4C5mqr',
      stripeCustomerId: 'cus_LCzDytWWulJQwW',
      stripeProductId: 'prod_JhyG9dRdTHYCte',
      userId: 94,
      userName: 'Nadia Sharifi',
      productId: 9,
      productName: 'Grove Membership ($60/yr = 3 trees/yr)',
      email: 'n77sharifi@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 44,
      createdDate: '2020-02-13T01:49:29.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-13T01:53:03.000Z',
      status: 'active',
      stripeId: 'sub_GiynoovuGaxrxb',
      stripeCustomerId: 'cus_GiynWzYgrH5nSc',
      stripeProductId: 'prod_G7kmYy8tIXJI6E',
      userId: 46,
      userName: 'Xanetta Miller',
      productId: 12,
      productName: 'TFYP Tree Donation',
      email: 'xanettamiller@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 80,
      createdDate: '2021-02-04T16:10:09.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-04T16:13:43.000Z',
      status: 'active',
      stripeId: 'sub_IswHzUs0C3OiPT',
      stripeCustomerId: 'cus_IswH8qftlmKMTD',
      stripeProductId: 'prod_HWl8O9XK4U099w',
      userId: 78,
      userName: 'Mina Sucur',
      productId: 3,
      productName: 'TFYP Tree Donation',
      email: 'Mina.sucur@gmail.com',
      hasShirt: true,
      amount: 100,
    },
    {
      id: 7,
      createdDate: '2021-02-04T01:44:07.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-04T01:44:26.000Z',
      status: 'active',
      stripeId: 'sub_IsiJRw5XsWfEZ9',
      stripeCustomerId: 'cus_IsiJO9vb9FQtCu',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 8,
      userName: 'Tracy Heim',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'tracyheim@utexas.edu',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 4,
      createdDate: '2021-02-03T04:16:20.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-02-03T04:17:38.000Z',
      status: 'active',
      stripeId: 'sub_IsNY4YtClvHUv9',
      stripeCustomerId: 'cus_IsNXERU8fedqca',
      stripeProductId: 'prod_HWl8O9XK4U099w',
      userId: 3,
      userName: 'Timothy Brown',
      productId: 3,
      productName: 'TFYP Tree Donation',
      email: 'timb12891@gmail.com',
      hasShirt: false,
      amount: 100,
    },
    {
      id: 99,
      createdDate: '2022-01-26T20:35:15.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-01-26T20:35:15.000Z',
      status: 'active',
      stripeId: 'sub_1KMID1KRkjW3h5nxvMkg55Q8',
      stripeCustomerId: 'cus_L2Mw7KzawEzs1b',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 93,
      userName: null,
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'lexi.li.elio@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 98,
      createdDate: '2022-01-24T10:45:42.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-01-24T10:45:42.000Z',
      status: 'active',
      stripeId: 'sub_1KLQ3OKRkjW3h5nx4nXrWXVx',
      stripeCustomerId: 'cus_L1Sz93LZcGQr8X',
      stripeProductId: 'prod_L1SzAOSor1qY9q',
      userId: 92,
      userName: 'Kathleen Moody',
      productId: 34,
      productName: 'Forest+ Membership ($200/yr = 10 trees/yr)',
      email: 'katmoody525@gmail.com',
      hasShirt: false,
      amount: 200,
    },
    {
      id: 9,
      createdDate: '2021-01-20T15:58:20.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-01-20T16:00:59.000Z',
      status: 'active',
      stripeId: 'sub_InJi1R0nel8weC',
      stripeCustomerId: 'cus_InJiL2t88p2GFE',
      stripeProductId: 'prod_HWl8O9XK4U099w',
      userId: 10,
      userName: 'Lauren Masey',
      productId: 3,
      productName: 'TFYP Tree Donation',
      email: 'lauren@gmail.com',
      hasShirt: false,
      amount: 100,
    },
    {
      id: 55,
      createdDate: '2020-01-18T15:05:14.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-01-18T15:06:07.000Z',
      status: 'active',
      stripeId: 'sub_GZRkXn3LklqgSj',
      stripeCustomerId: 'cus_GZRk1bnIGoVOQW',
      stripeProductId: 'prod_G74eNUS803eHaY',
      userId: 56,
      userName: 'Armando Sanchez',
      productId: 8,
      productName: 'TFYP Tree Donation',
      email: 'armando.8786@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 16,
      createdDate: '2021-01-06T15:46:07.000Z',
      expirationDate: null,
      lastPaymentDate: '2022-01-06T15:48:05.000Z',
      status: 'active',
      stripeId: 'sub_Ii4LaMBA9t460N',
      stripeCustomerId: 'cus_Ii4LqAVO3OrGcT',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 19,
      userName: 'Anna Dabrowski',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'treefolks@ajdabrowski.net',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 97,
      createdDate: '2021-12-30T21:28:59.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-12-30T21:28:59.000Z',
      status: 'active',
      stripeId: 'sub_1KCWBDKRkjW3h5nxqueiUIBs',
      stripeCustomerId: 'cus_KsGirT3hez8YKM',
      stripeProductId: 'prod_JhyG9dRdTHYCte',
      userId: 91,
      userName: 'Rachel Wright',
      productId: 9,
      productName: 'Grove Membership ($60/yr = 3 trees/yr)',
      email: 'rachel.wright156@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 96,
      createdDate: '2021-12-18T20:05:49.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-12-18T20:05:49.000Z',
      status: 'active',
      stripeId: 'sub_1K89A9KRkjW3h5nxZNefWmj1',
      stripeCustomerId: 'cus_Knkf5tTSnEw4Eo',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 90,
      userName: 'Aaron Sandel',
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'aaron.sandel@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 2,
      createdDate: '2020-12-09T18:52:39.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-12-09T18:52:56.000Z',
      status: 'active',
      stripeId: 'sub_IXd2PHhEpO1A4g',
      stripeCustomerId: 'cus_IXd2HRVZ9MtYF5',
      stripeProductId: 'prod_HFMvRwD9RYTePo',
      userId: 2,
      userName: null,
      productId: 2,
      productName: 'TreeFolks Young Professionals Annual Donation',
      email: 'paul.difiore@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 51,
      createdDate: '2019-11-21T00:32:51.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-11-21T00:33:14.000Z',
      status: 'active',
      stripeId: 'sub_GDUaCxbXhfanGM',
      stripeCustomerId: 'cus_GDUaFoqzfWB8K6',
      stripeProductId: 'prod_G7kmYy8tIXJI6E',
      userId: 52,
      userName: 'Adam Garrett',
      productId: 12,
      productName: 'TFYP Tree Donation',
      email: 'acg0904@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 82,
      createdDate: '2019-11-14T15:12:51.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-11-14T15:13:26.000Z',
      status: 'active',
      stripeId: 'sub_GB6CPnjooypOUX',
      stripeCustomerId: 'cus_GB6CbybDB8tYBz',
      stripeProductId: 'prod_G74eNUS803eHaY',
      userId: 72,
      userName: 'Jenn Rashid',
      productId: 8,
      productName: 'TFYP Tree Donation',
      email: 'Rashidjennifer3@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 8,
      createdDate: '2020-11-13T23:38:37.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-11-13T23:38:53.000Z',
      status: 'active',
      stripeId: 'sub_INxmP24Y7pGfXQ',
      stripeCustomerId: 'cus_INxmeKw4fKREBx',
      stripeProductId: 'prod_INxmgMZBOkB5D2',
      userId: 7,
      userName: 'Annette Morales',
      productId: 6,
      productName: 'TreeFolks Young Professionals Annual Donation',
      email: 'annette.mora04@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 92,
      createdDate: '2021-11-09T02:18:26.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-11-09T02:18:27.000Z',
      status: 'active',
      stripeId: 'sub_1JtjupKRkjW3h5nxwpxUJJUj',
      stripeCustomerId: 'cus_KYrexR4WYyDoCU',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 86,
      userName: 'Megan Pritts',
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'prittsm@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 23,
      createdDate: '2019-11-05T16:52:42.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-11-05T16:53:00.000Z',
      status: 'active',
      stripeId: 'sub_G7kmr9VbBQ6Pej',
      stripeCustomerId: 'cus_G7kmF1qPqpA194',
      stripeProductId: 'prod_G7kmYy8tIXJI6E',
      userId: 26,
      userName: 'Steven Van Landingham',
      productId: 12,
      productName: 'TFYP Tree Donation',
      email: 'steven.vanlandingham@yahoo.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 1,
      createdDate: '2020-10-15T22:01:55.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-10-15T22:01:57.000Z',
      status: 'active',
      stripeId: 'sub_ID4fnucgQ1wBaK',
      stripeCustomerId: 'cus_ID4fahrSjcjt1t',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 1,
      userName: 'Richard Hammond',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'rjh5244@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 86,
      createdDate: '2021-10-13T12:22:23.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-10-13T12:22:23.000Z',
      status: 'active',
      stripeId: 'sub_1Jk6TTKRkjW3h5nx3oSSctcG',
      stripeCustomerId: 'cus_Ew9QrSYURpHGg3',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 80,
      userName: null,
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'yp@treefolks.org',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 90,
      createdDate: '2021-10-13T05:22:11.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-10-13T05:22:11.000Z',
      status: 'active',
      stripeId: 'sub_1JjzupKRkjW3h5nxKHgYsNfP',
      stripeCustomerId: 'cus_KOnVgsPBzFYgbO',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 84,
      userName: 'Sway Bhaduri',
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'sbhaduri@ualberta.ca',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 14,
      createdDate: '2020-10-12T05:08:09.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-10-12T05:08:19.000Z',
      status: 'active',
      stripeId: 'sub_IBgdl4JwA7DGIm',
      stripeCustomerId: 'cus_IBgdxA8Um69QlV',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 17,
      userName: 'Andy Dosmann',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'dosmann1@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 57,
      createdDate: '2020-10-09T17:43:29.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-10-09T17:43:54.000Z',
      status: 'active',
      stripeId: 'sub_IAl9B0y84Dpu6r',
      stripeCustomerId: 'cus_IAl9yyrrcgwtir',
      stripeProductId: 'prod_HFMvRwD9RYTePo',
      userId: 58,
      userName: 'Elyse Ensor',
      productId: 2,
      productName: 'TreeFolks Young Professionals Annual Donation',
      email: 'elyse.ensor@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 3,
      createdDate: '2021-09-14T19:44:03.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-09-14T19:44:03.000Z',
      status: 'active',
      stripeId: 'sub_1JZhXzKRkjW3h5nx06xkUjRi',
      stripeCustomerId: 'cus_KE9ruO1bieGtEJ',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 4,
      userName: 'Cassandra Machart',
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'cmacha01@leeu.edu',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 11,
      createdDate: '2020-08-23T02:35:45.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-08-23T02:36:16.000Z',
      status: 'active',
      stripeId: 'sub_Hsutp8NxB7YZsI',
      stripeCustomerId: 'cus_Hsut8yM5nL1Uuj',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 15,
      userName: 'Thomas Logan',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'thomaslilogan@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 28,
      createdDate: '2020-08-07T22:32:07.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-08-07T22:32:31.000Z',
      status: 'active',
      stripeId: 'sub_HnEZl3a3YwfBv1',
      stripeCustomerId: 'cus_HnEZyERegswLOe',
      stripeProductId: 'prod_HWl8O9XK4U099w',
      userId: 33,
      userName: 'Bear Bustillo',
      productId: 3,
      productName: 'TFYP Tree Donation',
      email: 'bearbustillo@gmail.com',
      hasShirt: false,
      amount: 100,
    },
    {
      id: 27,
      createdDate: '2020-07-30T11:56:12.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-07-30T11:56:29.000Z',
      status: 'active',
      stripeId: 'sub_Hk4ViUXn5uG7gG',
      stripeCustomerId: 'cus_Hk4Vrc71OQh2kk',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 32,
      userName: 'Nicholas Cianciara',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'nacianciara@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 19,
      createdDate: '2021-07-15T01:26:46.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-07-15T01:26:47.000Z',
      status: 'active',
      stripeId: 'sub_Jr1OdvugD6luss',
      stripeCustomerId: 'cus_Jr1O7uFee80prv',
      stripeProductId: 'prod_JhyG9dRdTHYCte',
      userId: 23,
      userName: 'Milorad Sucur',
      productId: 9,
      productName: 'Grove Membership ($60/yr = 3 trees/yr)',
      email: 'msucuryh@yahoo.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 68,
      createdDate: '2020-07-08T18:50:32.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-07-08T18:50:34.000Z',
      status: 'active',
      stripeId: 'sub_HbwEEXs5W4oerF',
      stripeCustomerId: 'cus_HbwEJNrWailOhu',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 68,
      userName: 'Jeanette Lachman',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'jeanettelachman@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 21,
      createdDate: '2020-07-01T02:50:30.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-07-01T02:50:47.000Z',
      status: 'active',
      stripeId: 'sub_HZ4A5GugscT86E',
      stripeCustomerId: 'cus_HZ4ADlFqXQePSZ',
      stripeProductId: 'prod_HWl8O9XK4U099w',
      userId: 24,
      userName: 'Lisa Notier',
      productId: 3,
      productName: 'TFYP Tree Donation',
      email: 'lisa.notier@gmail.com',
      hasShirt: false,
      amount: 100,
    },
    {
      id: 24,
      createdDate: '2020-06-24T23:02:26.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-24T23:02:39.000Z',
      status: 'active',
      stripeId: 'sub_HWl85mIkO47NFG',
      stripeCustomerId: 'cus_HWl88nQNa5YTd7',
      stripeProductId: 'prod_HWl8O9XK4U099w',
      userId: 30,
      userName: 'Matthew Bostwick',
      productId: 3,
      productName: 'TFYP Tree Donation',
      email: 'matthewbostwick@gmail.com',
      hasShirt: false,
      amount: 100,
    },
    {
      id: 56,
      createdDate: '2018-06-22T17:01:04.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-22T17:01:45.000Z',
      status: 'active',
      stripeId: 'sub_D64ml4LeR3YEuj',
      stripeCustomerId: 'cus_D64mlZKCiRhYHa',
      stripeProductId: 'prod_D2WyOQQAcvV40e',
      userId: 57,
      userName: 'KELSEY WEAVER',
      productId: 18,
      productName: 'TFYP Tree Donation',
      email: 'kelseyweaver@utexas.edu',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 29,
      createdDate: '2019-06-20T23:42:17.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-20T23:42:18.000Z',
      status: 'active',
      stripeId: 'sub_FIADm9typGni8o',
      stripeCustomerId: 'cus_FIADy9ofi6jWPr',
      stripeProductId: 'prod_FIAAHm7JfWP6fg',
      userId: 34,
      userName: 'Clark Bockhahn',
      productId: 13,
      productName: 'TFYP Tree Donation',
      email: 'Clark.bockhahn@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 13,
      createdDate: '2021-06-20T21:36:27.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-20T21:36:27.000Z',
      status: 'active',
      stripeId: 'sub_JhyGAoBpEYmZCy',
      stripeCustomerId: 'cus_JhyGp628CfSfPi',
      stripeProductId: 'prod_JhyG9dRdTHYCte',
      userId: 12,
      userName: 'Mackenzie Anderson',
      productId: 9,
      productName: 'Grove Membership ($60/yr = 3 trees/yr)',
      email: 'mackenzieanderson91@me.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 36,
      createdDate: '2020-06-20T15:36:52.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-20T15:37:23.000Z',
      status: 'active',
      stripeId: 'sub_HV925ZS7ABU6FR',
      stripeCustomerId: 'cus_HV92IKBRBV2D4s',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 41,
      userName: 'Courtney Donilon',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'courtney.donilon@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 48,
      createdDate: '2018-06-17T14:10:00.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-17T14:10:08.000Z',
      status: 'active',
      stripeId: 'sub_D49tSjDJuMCbNG',
      stripeCustomerId: 'cus_D49tslESmg5X7x',
      stripeProductId: 'prod_D2WyOQQAcvV40e',
      userId: 49,
      userName: 'Adam Odrobina',
      productId: 18,
      productName: 'TFYP Tree Donation',
      email: 'adamodrobina@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 6,
      createdDate: '2021-06-01T22:57:26.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-06-01T22:57:26.000Z',
      status: 'active',
      stripeId: 'sub_JasHQRPExMWRio',
      stripeCustomerId: 'cus_JasHxgGdrudZqR',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 9,
      userName: 'Gabriel Reyna',
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'Gabrielreyna@makeyourdaysa.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 39,
      createdDate: '2019-05-16T22:47:30.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-05-16T22:47:46.000Z',
      status: 'active',
      stripeId: 'sub_F52RnWb3474WUa',
      stripeCustomerId: 'cus_F52RI8goUXhUcw',
      stripeProductId: 'prod_F52RlSXNnJz6jx',
      userId: 42,
      userName: 'Margot Piper',
      productId: 19,
      productName: 'TFYP Tree Donation',
      email: 'margotvpiper@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 15,
      createdDate: '2021-05-15T15:25:09.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-05-15T15:25:10.000Z',
      status: 'active',
      stripeId: 'sub_JUO81ilH5yNMx2',
      stripeCustomerId: 'cus_JUO8PyMFnNWxan',
      stripeProductId: 'prod_JUO8cHuAiRgYrV',
      userId: 18,
      userName: 'Anna Wood',
      productId: 4,
      productName: 'Single Tree Membership ($20/yr = 1 tree/yr)',
      email: 'annawood613@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 25,
      createdDate: '2020-05-06T18:07:25.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-05-06T18:07:31.000Z',
      status: 'active',
      stripeId: 'sub_HEKJ5BNRri5rNl',
      stripeCustomerId: 'cus_HEKJboCmFznHDb',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 29,
      userName: 'Joseph Hurtekant',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'joseph.hurtekant@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 5,
      createdDate: '2020-04-26T13:41:36.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-04-26T13:42:22.000Z',
      status: 'active',
      stripeId: 'sub_HAVlECGLajSeOp',
      stripeCustomerId: 'cus_HAVl5Nu0N1KKKB',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 6,
      userName: 'James Odom',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'jcodom2@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 22,
      createdDate: '2021-04-09T20:39:03.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-04-09T20:39:03.000Z',
      status: 'active',
      stripeId: 'sub_JGz4uasy9uKLOU',
      stripeCustomerId: 'cus_JGz4SM11ZF8jUz',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 28,
      userName: 'Hannah Riemer',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'hriemer@lja.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 26,
      createdDate: '2020-02-24T22:48:22.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-02-24T22:48:43.000Z',
      status: 'past_due',
      stripeId: 'sub_GnQa3AvUruZm64',
      stripeCustomerId: 'cus_GnQaoyIBl1Echl',
      stripeProductId: 'prod_GnQaMh1P930PrB',
      userId: 31,
      userName: 'Alejandra Rodriguez Boughton',
      productId: 7,
      productName: 'TFYP Tree Donation',
      email: 'ale@laflacaatx.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 60,
      createdDate: '2020-02-13T01:57:13.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-02-13T01:57:28.000Z',
      status: 'past_due',
      stripeId: 'sub_GiyuLGicnKiDfI',
      stripeCustomerId: 'cus_GiyukfaRgkPpDF',
      stripeProductId: 'prod_G7kmYy8tIXJI6E',
      userId: 62,
      userName: 'William Maas',
      productId: 12,
      productName: 'TFYP Tree Donation',
      email: 'Tmaas44@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 17,
      createdDate: '2021-02-02T15:59:05.000Z',
      expirationDate: null,
      lastPaymentDate: '2021-02-02T15:59:05.000Z',
      status: 'past_due',
      stripeId: 'sub_IsBeAJI6rPOiQ4',
      stripeCustomerId: 'cus_IsBeu0lerDdb4F',
      stripeProductId: 'prod_HAVl2LI8VgS5Np',
      userId: 20,
      userName: 'Caitlin Caven',
      productId: 1,
      productName: 'TFYP Tree Donation',
      email: 'Caitlin.caven@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 81,
      createdDate: '2019-11-22T00:56:05.000Z',
      expirationDate: null,
      lastPaymentDate: '2020-11-22T00:56:28.000Z',
      status: 'past_due',
      stripeId: 'sub_GDsBtCvsT50Ssm',
      stripeCustomerId: 'cus_GDsB4EyCbAlnpQ',
      stripeProductId: 'prod_G74eNUS803eHaY',
      userId: 79,
      userName: 'Zachary Callahan',
      productId: 8,
      productName: 'TFYP Tree Donation',
      email: 'zcallahan47@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 70,
      createdDate: '2019-11-13T23:15:58.000Z',
      expirationDate: null,
      lastPaymentDate: '2020-11-13T23:18:03.000Z',
      status: 'past_due',
      stripeId: 'sub_GAqlBCL5OOjpoG',
      stripeCustomerId: 'cus_GAqlacfjlYDjp7',
      stripeProductId: 'prod_G7kmYy8tIXJI6E',
      userId: 69,
      userName: 'Saxton Archer',
      productId: 12,
      productName: 'TFYP Tree Donation',
      email: 'cascadearcher@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 41,
      createdDate: '2019-11-13T21:24:50.000Z',
      expirationDate: null,
      lastPaymentDate: '2020-11-13T21:25:24.000Z',
      status: 'past_due',
      stripeId: 'sub_GAoy7pZnnKeLFr',
      stripeCustomerId: 'cus_GAoymfwzYrvBq8',
      stripeProductId: 'prod_G7kmYy8tIXJI6E',
      userId: 44,
      userName: 'Jennifer Klingshirn',
      productId: 12,
      productName: 'TFYP Tree Donation',
      email: 'jklingshirn89@gmail.com',
      hasShirt: false,
      amount: 60,
    },
    {
      id: 18,
      createdDate: '2020-02-13T01:50:37.000Z',
      expirationDate: null,
      lastPaymentDate: '2020-02-13T01:50:37.000Z',
      status: 'past_due',
      stripeId: 'sub_Giyof48pTgmKGl',
      stripeCustomerId: 'cus_Giyo8DGe32cXdQ',
      stripeProductId: 'prod_G74eNUS803eHaY',
      userId: 22,
      userName: 'Tori Bloom',
      productId: 8,
      productName: 'TFYP Tree Donation',
      email: 'toribloom4@gmail.com',
      hasShirt: false,
      amount: 20,
    },
    {
      id: 10,
      createdDate: '2020-02-13T01:48:58.000Z',
      expirationDate: null,
      lastPaymentDate: '2020-02-13T01:48:58.000Z',
      status: 'past_due',
      stripeId: 'sub_GiymPqhc6mEY4V',
      stripeCustomerId: 'cus_GiymtSrh0VvAHl',
      stripeProductId: 'prod_G74eNUS803eHaY',
      userId: 11,
      userName: 'Maureen Sweet',
      productId: 8,
      productName: 'TFYP Tree Donation',
      email: 'maureen.p.sweet@gmail.com',
      hasShirt: false,
      amount: 20,
    },
  ]) as SubscriptionWithDetails[];

  const stats: Stats = {
    active: 0,
    newActive: 0,
    newInactive: 0,
    percentageByYear: [],
  };

  const calendarYear = new Date();
  calendarYear.setDate(calendarYear.getDate() - 365);

  const calendarYearPlusWindow = new Date(
    new Date().getTime() - (new Date().getTime() - calendarYear.getTime()) + (dateFilter.getTime() - new Date().getTime()),
  );

  const inactiveAfterYearMap: Record<number, number> = {};
  const memberCountByYear: Record<number, number> = {};

  subscriptionWithDetails.forEach(item => {
    const memberYears = item.lastPaymentDate.getFullYear() - item.createdDate.getFullYear() + 1;

    if (!memberCountByYear[memberYears - 1]) memberCountByYear[memberYears - 1] = 0;
    memberCountByYear[memberYears - 1]++;

    if (item.createdDate > dateFilter) stats.newActive++;

    if (item.lastPaymentDate > calendarYear) stats.active++;
    else {
      if (item.lastPaymentDate > calendarYearPlusWindow) stats.newInactive++;

      if (!inactiveAfterYearMap[memberYears]) inactiveAfterYearMap[memberYears] = 0;
      inactiveAfterYearMap[memberYears]++;
    }
  });

  const keys = Object.keys(memberCountByYear);
  keys.shift();

  let inactiveCount = 0;

  const percentageByYear = keys.map((key: string) => {
    const yearCount = Number(key);
    if (inactiveAfterYearMap[yearCount]) {
      inactiveCount += inactiveAfterYearMap[yearCount];
    }
    const totalCount = keys.reduce((previousValue, currentValue) => {
      const currentYear = Number(currentValue);
      if (currentYear > 1 && currentYear <= yearCount && inactiveAfterYearMap[currentYear - 1])
        previousValue += inactiveAfterYearMap[currentYear - 1];

      if (currentYear < yearCount) return previousValue;
      else {
        return (previousValue += memberCountByYear[currentYear]);
      }
    }, 0);
    return Math.round((1 - inactiveCount / totalCount) * 100);
  });

  stats.percentageByYear = percentageByYear;

  res.status(200).json(stats);
}
